### ISSUE TITLE
Trouble with the pre-req's

### ISSUE THREAD

**Issue by ghost** [tfoldi/fuse-tableaufs#1]
Hi Földi,

I'm really looking forward to using this, but have problem on OSX with the pre-requisites.

These are the error messages.  Could you perhaps help me to understand what's missing ?

$ cmake . && make && make install
-- Build type: 
-- C FLAGS:      -DDEBUG -g3  -Wall -Wwrite-strings -Wcast-qual -Wpointer-arith -Wconversion -Wcomment -Wcast-align -Wshadow -Wredundant-decls  
-- Found PostgreSQL: /usr/local/Cellar/postgresql/9.4.1/lib/libpq.dylib
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/keithhelfrich/Private/RHSD.io/repos/fuse-tableaufs
[ 33%] Building C object src/CMakeFiles/tableaufs.dir/tableaufs.c.o
clang: error: no input files
/bin/sh: -D_DARWIN_USE_64_BIT_INODE: command not found
make[2]: **\* [src/CMakeFiles/tableaufs.dir/tableaufs.c.o] Error 127
make[1]: **\* [src/CMakeFiles/tableaufs.dir/all] Error 2
make: **\* [all] Error 2

Thanks!

**Comment by tfoldi** [comment]
When pkg-config returns multiple items it adds a plus ; character which caused the cmake script error. This one is fixed as well an osxfuse related segfault problem. Merged 

Pull request https://github.com/tfoldi/fuse-tableaufs/pull/2 merged, please pull again and recompile - it should work.
