### ISSUE TITLE
Tableau 10.2 some workbooks aren't showing up

### ISSUE THREAD

**Issue by r-richmond** [tfoldi/fuse-tableaufs#7]
First off, really cool tool!

Secondly,

I'm trying to use this software to prototype and external backup in git. 

However, I've noticed that this isn't listing all of the workbooks present on the server. To your knowledge has anything changed in the past year or so that would cause it to break?

(1200/1500 workbooks show up leaving about 300 unaccounted for).

edit: I've granted select on the large objects for readonly and the missing workbooks don't appear to be following a size pattern.

**Comment by Charles-Ayotte-Trepanier** [comment]
Same here! It seems only dashboards published years ago are showing. We went from 9.2 to 10.1 and then 10.2. I don't think anything that is version 10.1 or 10.2 appears in the file system.

**Comment by tfoldi** [comment]
Sorry guys, I just fixed it in 28d43cb80908bc7b722b4ea20db5880b8fecbb0a 

From now the master branch is only compatible with 10.3
