### ISSUE TITLE
It is only possible to override existing files #: cannot # ‘somefile’: Function not implemented

### ISSUE THREAD

**Issue by 1oglop1** [tfoldi/fuse-tableaufs#8]
I tried several operations with tableau FS.
And it seems that it only supports reading and writing to the same files.

But when I tried to create new file I got error above or `cp: cannot create regular file ... : Function not implemented`

The question is how can I leverage tableauFS to move workbooks and sites between servers?
Is it even possible?

Thank you.

**Comment by tfoldi** [comment]
No, unfortunately, you cannot publish new files. It support overwrite but not publishing :(
