### ISSUE TITLE
 error reading Operation not permitted with readonly user

### ISSUE THREAD

**Issue by xakraz** [tfoldi/fuse-tableaufs#9]
Hello @tfoldi,

First, thank you for this tool !

Unfortunately, I face an issue with it.
- [x] I followed the steps to prepare the `readonly` user
- [x] I run successfully the container from DockerHub
- [x] I can browser the FS from the container

BUT I can not get or copy files to my local FS (or somewhere else in the container)

Any idea where this issue might come from ?

**Comment by tfoldi** [comment]
did you grant SELECT right to your user on `pg_largeobjects` ? Steps to perform described here: https://github.com/tfoldi/fuse-tableaufs#configuring-tableau-server-database
